import os
import time

blue = '\033[34;1m'
green = '\033[32;1m'
purple = '\033[35;1m'
cyan = '\033[36;1m'
red = '\033[31;1m'
white = '\033[37;1m'
yellow = '\033[33;1m'

print(red),("[1 ]install--MBF (Multi Bruteforce Facebook)")
print(yellow),("[2 ]install--LITEDDOS (DDOS Situs)")
print(green),("[3 ]install--LITESCRIPT (Buat Script deface.html)")
print(blue),("[4 ]install--BAJINGANv6 (200 Tools Termux)")
print(white),("[5 ]install--OSIF (Open Souce Information Facebook)")
print(purple),("[6 ]install--RED_HAWK (Scanning Website)")
print(red),("[7 ]install--weeman (Bikin Web Phising!)")
print(yellow),("[8 ]install--PhisingGame (Bikin web Phising ML&COC)")
print(green),("[9 ]install--NewscatBOT (Nuyul Newscat!)")
print(blue),("[10]install--kubik-bot (Nuyul Kubik!)")
print(white),("[11]install--sqlmap (Inject Web Vuln SQLi)")
print(purple),("[12]install--KumpulanFbbrute (Kumpulan BruteForce FB)")
print(red),("[13]install--LITESPAM (Spammer Sms)")
print(yellow),("[14]install--MCR (Media Converter Termux)")
print(green),("[15]install--mantan.py (SpamSms)")
print(blue),("[16]install--BotKomema (Bot Komen Fb)")
print(white),("[17]install--diejoubu (Scanning Website Tools)")
print(purple),("[18]install--ipcs (Hack CCTV)")
print(red),("[19]")
print(yellow),("[20]")
print(green),("[21]")
print(blue),("[22]")
print(white),("[23]")
print(purple),("[24]")
print(red),("[25]")
print(yellow),("[26]")
print(green),("[27]")
print(blue),("[28]")
print(white),("[29]")
print(purple),("[30]")
print(red),("[31]")
print(yellow),("[32]")
print(green),("[33]")
print(blue),("[34]")
print(white),("[35]")
print(purple),("[36]")
print(red),("[37]")
print(yellow),("[38]")
print(green),("[39]")
print(blue),("[40]")
print(white),("[41]")
print(purple),("[42]")
print(red),("[43]")
print(yellow),("[44]")
print(green),("[45]")
print(blue),("[46]")
print(white),("[47]")
print(purple),("[48]")
print(red),("[49]")
print(yellow),("[50]")
print(red),("[+]------------------------------------------------[-]")
print(green),"[ Script By:",(blue),"Termux/Programing Tools & app berfaedah]"
print(green),"[ Since    :",(white),"20 Oktober 2018                        ]"
print(green),"[ Support  :",(yellow),"All who have liked the page            ]"
print(red),("[+]------------------------------------------------[-]")
pilih = input(" Pilih No: ")

if pilih ==1:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install python2')
    os.system ('pip2 install mechanize')
    os.system ('pip2 install --upgrade pip')
    os.system ('git clone https://github.com/YukersCreew/mbf')
    os.chdir ('mbf')
    os.system ('clear')
    os.system ('python2 MBF.py')
        
if pilih ==2:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install python2')
    os.system ('git clone https://github.com/4L13199/LITEDDOS')
    os.chdir ('LITEDDOS')
    os.system ('clear')
    print (yellow)
    print ("Jalankan dg ketik perintah:")
    time.sleep(2.0)
    print ("$ cd LITEDDOS")
    time.sleep(2.0)
    print ("$ python2 LITEDDOS.py <ip> <port> <packet>")
    
if pilih ==3:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install python2')
    os.system ('git clone https://github.com/4L13199/LITESCRIPT')
    os.chdir ('LITESCRIPT')
    os.system ('clear')
    os.system ('python2 LITESCRIPT.py')

if pilih ==4:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pip2 install --upgrade pip')
    os.system ('pip2 install termcolor')
    os.system ('pip2 install lolcat')
    os.system ('apt install toilet')
    os.system ('git clone https://github.com/DarknessCyberTeam/BAJINGANv6')
    os.chdir ('BAJINGANv6')
    os.system ('clear')
    print(green),('inget!')
    print(red),('Username: BAJINGAN')
    print(red),('Password: Gans')
    time.sleep (5.5)
    os.system ('sh BAJINGAN.sh')
if pilih ==5:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pip2 install --upgrade pip')
    os.system ('pip2 install requests mechanize')
    os.system ('git clone https://github.com/CiKu370/OSIF')
    os.chdir ('OSIF')
    os.system ('pip2 install -r requirements.txt')
    os.system ('clear')
    print(red),('ketik token (untuk login fb)')
    time.sleep(1.0)
    print(red),('ketik help (untuk melihat bantuan)')
    time.sleep(1.5)
    os.system ('python2 osif.py')
if pilih ==6:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install php')
    os.system ('pkg install curl')
    os.system ('git clone https://github.com/Tuhinshubhra/RED_HAWK')
    os.chdir ('RED_HAWK')
    os.system ('clear')
    os.system ('php rhawk.php')
if pilih ==7:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt-get update')
    os.system ('apt-get upgrade')
    os.system ('git clone https://github.com/evait-security/weeman')
    os.chdir ('weeman')
    os.system ('clear')
    os.system ('python2 weeman.py')
if pilih ==8:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('git clone https://github.com/Senitopeng/PhisingGame')
    os.chdir ('PhisingGame')
    os.system ('clear')
    os.system ('python2 phising.py')
if pilih ==9:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade && apt install python2 && apt install curl && apt install wget && apt install bash && apt install grep')
    os.system ('git clone https://github.com/kadalsinus/NewscatBOT')
    os.chdir ('NewscatBOT')
    os.system ('chmod +x BOT.sh')
    os.system ('clear')
    os.system ('sh BOT.sh')
if pilih ==10:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pkg install php')
    os.system ('git clone https://github.com/radenvodka/kubik-bot')
    os.chdir ('kubik-bot')
    os.system ('pkg install nano')
    os.system ('nano kubik.php')
if pilih ==11:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('git clone https://github.com/sqlmapproject/sqlmap.git')
    os.chdir ('sqlmap')
    os.system ('chmod +x sqlmap.py && chmod +x sqlmapapi.py')
    os.system ('clear')
    print(blue),('jalankan dg perintah:')
    time.sleep (1.7)
    print(blue),('cd sqlmap')
    print(blue),('python2 sqlmap.py -u <web vuln>')
if pilih ==12:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade -y')
    os.system ('pkg install php')
    os.system ('pip2 install --upgrade pip')
    os.system ('pip2 install mechanize')
    os.system ('git clone https://github.com/Senitopeng/KumpulanFbbrute.git')
    os.chdir ('KumpulanFbbrute')
    os.system ('clear')
    os.system ('python2 jomblo.py')
if pilih ==13:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('pkg update && pkg upgrade')
    os.system ('pkg install php')
    os.system ('pkg install toilet')
    os.system ('git clone https://github.com/4L13199/LITESPAM')
    os.chdir ('LITESPAM')
    os.system ('clear')
    os.system ('sh LITESPAM.sh')
if pilih ==14:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('pkg update && pkg upgrade')
    os.system ('git clone https://github.com/iqbalfaf/MCT')
    os.chdir ('MCT')
    os.system ('chmod +x install.sh')
    os.system ('clear')
    os.system ('sh install.sh')
if pilih ==15:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('apt install php')
    os.system ('apt install nano')
    os.system ('pip2 install requests')
    os.system ('git clone https://github.com/Senitopeng/SpamSms.git')
    os.chdir ('SpamSms')
    os.system ('chmod +x mantan.py')
    os.system ('clear')
    os.system ('python2 mantan.py')
if pilih ==16:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pip2 install mechanize')
    os.system ('git clone https://github.com/Senitopeng/Botkomena')
    os.chdir ('Botkomena')
    os.system ('clear')
    os.system ('python2 botkomena.py')
if pilih ==17:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('pkg update && pkg upgrade')
    os.system ('apt install php')
    os.system ('git clone https://github.com/alintamvanz/diejoubu')
    os.chdir ('diejoubu')
    os.chdir ('v1.2')
    os.system ('clear')
    os.system ('php daijobu.php')
if pilih ==18:
    os.system ('clear')
    os.system ('figlet "BYE"')
    os.system ('apt update && apt upgrade')
    os.system ('pip2 install requests')
    os.system ('git clone https://github.com/kancotdiq/ipcs')
    os.chdir ('ipcs')
    os.system ('python2 scan.py')


